# Generated by Django 5.2.5 on 2025-08-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.CharField(max_length=50)),
                ('raca', models.CharField(blank=True, max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, upload_to='pets/')),
            ],
        ),
    ]
