# Generated by Django 5.2.5 on 2025-08-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_adocao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adocao',
            name='usuario',
        ),
        migrations.AddField(
            model_name='adocao',
            name='email',
            field=models.EmailField(default='sememail@exemplo.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adocao',
            name='nome',
            field=models.CharField(default='Desconhecido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adocao',
            name='whatsapp',
            field=models.CharField(default='00000000000', max_length=20),
            preserve_default=False,
        ),
    ]
