# Generated by Django 4.2.23 on 2025-08-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('raca', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='pets/')),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
    ]
